### ISSUE TITLE
Protocol error between bokeh and dask distributed

### ISSUE THREAD

**Issue by caitlinadams** [GeoscienceAustralia/dea-sandbox#58] opened 2020-04-02 00:25 UTC
I'm currently running into the following issue whenever I try and start a local dask cluster in the default DE Africa Sandbox environment using the `create_local_dask()` function from [DE Africa Scripts](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Scripts/deafrica_dask.py):

```
tornado.application - ERROR - Uncaught exception GET /individual-progress/ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='sandbox.digitalearth.africa', method='GET', uri='/individual-progress/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/env/lib/python3.6/site-packages/bokeh/server/views/ws.py", line 123, in open
    raise ProtocolError("Subprotocol header is not 'bokeh'")
bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'
tornado.application - ERROR - Uncaught exception GET /individual-progress/ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='sandbox.digitalearth.africa', method='GET', uri='/individual-progress/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/env/lib/python3.6/site-packages/bokeh/server/views/ws.py", line 123, in open
    raise ProtocolError("Subprotocol header is not 'bokeh'")
bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'
tornado.application - ERROR - Uncaught exception GET /individual-progress/ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='sandbox.digitalearth.africa', method='GET', uri='/individual-progress/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/env/lib/python3.6/site-packages/bokeh/server/views/ws.py", line 123, in open
    raise ProtocolError("Subprotocol header is not 'bokeh'")
bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'
```

It might be linked to this thread: https://github.com/dask/distributed/issues/3593

As a consequence, dask appears to be working (data gets lazy loaded and then processed), but the dask dashboard is completely blank. 

![Screen Shot 2020-04-02 at 11 23 28 am](https://user-images.githubusercontent.com/25995927/78198496-78651280-74d4-11ea-9396-880ca1aa287e.png)

**Comment by tom-butler** [comment] 2020-04-02 01:11
@NikitaGandhi do you think this could be caused by calico or the firewall?

**Comment by Kirill888** [comment] 2020-04-21 00:01
Fixed by downgrading `bokeh` to latest pre-2 version.

**Closed by Kirill888** 2020-04-21 00:01 UTC
Labels: bug
